# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('siteNumber', models.CharField(blank=True, max_length=70, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=70, null=True)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
