# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='locality',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='lotBatchNum',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='catNumber',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='situation',
            new_name='totalUnits',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='site',
            new_name='unitsPerCase',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='siteNumber',
        ),
        migrations.AddField(
            model_name='entry',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
